### ISSUE TITLE
Dimensions-5.9.1 NPCUpdate-Log报错

### ISSUE THREAD

**Issue by Duck15** [popstarfreas/Dimensions#116]

**Comment by Duck15** [comment]
这是Log文件打包（之前不小心按到回车直接提交了空白信息，抱歉）
[logs.7z.zip](https://github.com/popstarfreas/Dimensions/files/10298771/logs.7z.zip)
版本:
[OTAPI] Starting up (OTAPI PC Server,3.1.19,9ab9fd1,ModFw:1.1.7).
TerrariaAPI Version: 2.1.0.0 (Protocol v1.4.4.8.1 (278), OTAPI 1.4.4.8)
TShock 5.1.2.0 (ζ Ori)
已开启SSC
维度版本:5.9.1(自行去除了版本修改部分)

**Comment by Duck15** [comment]
报错部分内容：
Wed Dec 14 2022 14:34:35 GMT+0800 (中国标准时间): TS Handle Data Error: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 27. Received 28
    at new NodeError (node:internal/errors:372:5)
    at boundsError (node:internal/buffer:86:9)
    at Buffer.readInt32LE (node:internal/buffer:390:5)
    at PacketReader.readInt32 (C:\Users\Administrator\Desktop\Dimensions-5.9.1-src - 副本\build\node_modules\dimensions\packets\bufferreader.js:109:34)
    at TerrariaServerPacketHandler.handleNPCUpdate (C:\Users\Administrator\Desktop\Dimensions-5.9.1-src - 副本\build\node_modules\dimensions\terrariaserverpackethandler.js:404:31)
    at TerrariaServerPacketHandler.handlePacket (C:\Users\Administrator\Desktop\Dimensions-5.9.1-src - 副本\build\node_modules\dimensions\terrariaserverpackethandler.js:93:32)
    at C:\Users\Administrator\Desktop\Dimensions-5.9.1-src - 副本\build\node_modules\dimensions\terrariaserver.js:51:53
    at arrayEach (C:\Users\Administrator\Desktop\Dimensions-5.9.1-src - 副本\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (C:\Users\Administrator\Desktop\Dimensions-5.9.1-src - 副本\node_modules\lodash\lodash.js:9368:14)
    at TerrariaServer.handleData (C:\Users\Administrator\Desktop\Dimensions-5.9.1-src - 副本\build\node_modules\dimensions\terrariaserver.js:50:15)

**Comment by ACaiCat** [comment]
It seems that Dimensions does not support latest TShock version.

**Comment by popstarfreas** [comment]
The latest is technically https://github.com/popstarfreas/Dimensions/releases/tag/v5.10.0-beta.1 , not 5.9.1. Is there a reason you're not testing using that version?

---

最新的在技术上是 https://github.com/popstarfreas/Dimensions/releases/tag/v5.10.0-beta.1 ，而不是 5.9.1。 您有没有使用该版本进行测试的原因？

**Comment by Duck15** [comment]
> The latest is technically https://github.com/popstarfreas/Dimensions/releases/tag/v5.10.0-beta.1 , not 5.9.1. Is there a reason you're not testing using that version?
> 
> 最新的在技术上是 https://github.com/popstarfreas/Dimensions/releases/tag/v5.10.0-beta.1 ，而不是 5.9.1。 您有没有使用该版本进行测试的原因？

RestApi on 7880 started.
[16240] Server on 7777 started.
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')

**Comment by Duck15** [comment]
Sun Dec 25 2022 14:33:43 GMT+0800 (中国标准时间): TS Handle Data Error: TypeError: Cannot read properties of undefined (reading 'indexOf')
    at TerrariaServerPacketHandler.handlePlayerInfo (C:\Users\Administrator\Desktop\Dimensions-v5.10.0-beta.1\build\node_modules\dimensions\terrariaserverpackethandler.js:529:146)
    at TerrariaServerPacketHandler.handlePacket (C:\Users\Administrator\Desktop\Dimensions-v5.10.0-beta.1\build\node_modules\dimensions\terrariaserverpackethandler.js:106:32)
    at C:\Users\Administrator\Desktop\Dimensions-v5.10.0-beta.1\build\node_modules\dimensions\terrariaserver.js:52:53
    at Array.forEach (<anonymous>)
    at TerrariaServer.handleData (C:\Users\Administrator\Desktop\Dimensions-v5.10.0-beta.1\build\node_modules\dimensions\terrariaserver.js:51:21)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by Duck15** [comment]
![V6`60{SKXX84E$%G1)7}GKR](https://user-images.githubusercontent.com/95078036/209459155-6feaa3ec-c0ce-4d8f-bee8-bc31b9cdfcef.jpg)
